name: "technology_config"
description: "This plant has HOPP wrapped up in it"

technologies:
  hopp:
    performance_model:
      model: "hopp"
      config: !include tech_inputs/hopp_config.yaml
    cost_model:
      model: "hopp"
  electrolyzer:
    performance_model:
      model: "pem_electrolyzer_performance"
    cost_model:
      model: "pem_electrolyzer_cost"
    model_inputs:
      shared_parameters:
        cluster_size_mw: 1.0
      performance_parameters:
        plant_life: 30
        eol_eff_percent_loss: 10
        uptime_hours_until_eol: 77600
        include_degradation_penalty: True
        turndown_ratio: 0.1
      cost_parameters:
        electrolyzer_cost: 2.
        