name: "technology_config"
description: "This plant has wind feeding into an electrolyzer with optimization"

technologies:
  wind:
    performance_model:
      model: "wind_plant_performance"
    cost_model:
      model: "wind_plant_cost"
    resource: 
      type: "pysam_wind"
      wind_speed: 9.
    model_inputs:  # need a much better name for this
      shared_parameters:
        num_turbines: 20
        turbine_rating_kw: 3000.0
      performance_parameters:
        rotor_diameter: 120.0
        hub_height: 100.0
        layout_mode: "grid"
        model_name: "pysam"
        model_input_file: null
        layout_params:
          border_spacing: 0.5
          border_offset: 0.5
          grid_angle: 2.0
          grid_aspect_power: 4.0
          row_phase_offset: 0.2
        rating_range_kw: [1000, 5000]
        floris_config: null
        operational_losses: 10.0
        timestep: [1, 60]
        fin_model: "default"
        name: "UtilityScaleWindPlant"
      cost_parameters:
        cost_per_kw: 1500.0
  electrolyzer:
    performance_model:
      model: "pem_electrolyzer_performance"
    cost_model:
      model: "pem_electrolyzer_cost"
    model_inputs:
      shared_parameters:
        cluster_size_mw: 1.0
      performance_parameters:
        plant_life: 30
        eol_eff_percent_loss: 10
        uptime_hours_until_eol: 77600
        include_degradation_penalty: True
        turndown_ratio: 0.1
      cost_parameters:
        electrolyzer_cost: 2.          
