name: "technology_config"
description: "This plant has a wind turbine, just one"

technologies:
  # Gen brought up idea to support multiple tech
  # definitions for a specific tech, e.g. multiple
  # battery types.
  wind:
    performance_model:
      model: "wind_plant_performance"
    cost_model:
      model: "wind_plant_cost"
    resource: 
      type: "pysam_wind"
      wind_speed: 9.
    model_inputs:
      shared_parameters:
        num_turbines: 20
        turbine_rating_kw: 3000.0
      performance_parameters:
        rotor_diameter: 120.0
        hub_height: 100.0
        layout_mode: "grid"
        model_name: "pysam"
        model_input_file: null
        layout_params:
          border_spacing: 0.5
          border_offset: 0.5
          grid_angle: 2.0
          grid_aspect_power: 4.0
          row_phase_offset: 0.2
        rating_range_kw: [1000, 5000]
        floris_config: null
        operational_losses: 10.0
        timestep: [1, 60]
        fin_model: "default"
        name: "UtilityScaleWindPlant"
      cost_parameters:
        cost_per_kw: 1500.0
  electrolyzer:
    performance_model:
      model: "dummy_electrolyzer_performance"
    cost_model:
      model: "dummy_electrolyzer_cost"