name: "technology_config"
description: "This plant has a wind farm and an ammonia plant"

technologies:
  wind:
    performance_model:
      model: "wind_plant_performance"
    cost_model:
      model: "wind_plant_cost"
    resource: 
      type: "pysam_wind"
      wind_speed: 9.
    model_inputs:
      shared_parameters:
        num_turbines: 20
        turbine_rating_kw: 3000.0
      performance_parameters:
        rotor_diameter: 120.0
        hub_height: 100.0
        layout_mode: "grid"
        model_name: "pysam"
        model_input_file: null
        layout_params:
          border_spacing: 0.5
          border_offset: 0.5
          grid_angle: 2.0
          grid_aspect_power: 4.0
          row_phase_offset: 0.2
        rating_range_kw: [1000, 5000]
        floris_config: null
        operational_losses: 10.0
        timestep: [1, 60]
        fin_model: "default"
        name: "UtilityScaleWindPlant"
      cost_parameters:
        cost_per_kw: 1500.0
  electrolyzer:
    performance_model:
      model: "pem_electrolyzer_performance"
    cost_model:
      model: "pem_electrolyzer_cost"
    model_inputs:
      shared_parameters:
        cluster_size_mw: 100.0
      performance_parameters:
        plant_life: 30
        eol_eff_percent_loss: 10
        uptime_hours_until_eol: 77600
        include_degradation_penalty: True
        turndown_ratio: 0.1
      cost_parameters:
        electrolyzer_cost: 2.
      financial_parameters:
        replacement_cost_percent: 0.

  ammonia:
    performance_model:
      model: "ammonia_performance"
    cost_model:
      model: "ammonia_cost"
    model_inputs:
      shared_parameters:
        plant_capacity_factor: 0.9
        plant_capacity_kgpy: 362560000.
      cost_parameters:
        feedstocks:
          electricity_cost: 93.83010424374427
          hydrogen_cost: 4.023963541079105
          cooling_water_cost: 0.00478
          iron_based_catalyst_cost: 23.19977341
          oxygen_cost: 0
