name: "technology_config"
description: "This plant has a wind farm and an ammonia plant"

technologies:
  wind:
    performance_model:
      model: "wind_plant_performance"
    cost_model:
      model: "wind_plant_cost"
    resource: 
      type: "pysam_wind"
      wind_speed: 9.
    model_inputs:
      shared_parameters:
        num_turbines: 20
        turbine_rating_kw: 3000.0
      performance_parameters:
        rotor_diameter: 120.0
        hub_height: 100.0
        layout_mode: "grid"
        model_name: "pysam"
        model_input_file: null
        layout_params:
          border_spacing: 0.5
          border_offset: 0.5
          grid_angle: 2.0
          grid_aspect_power: 4.0
          row_phase_offset: 0.2
        rating_range_kw: [1000, 5000]
        floris_config: null
        operational_losses: 10.0
        timestep: [1, 60]
        fin_model: "default"
        name: "UtilityScaleWindPlant"
      cost_parameters:
        cost_per_kw: 1500.0
  electrolyzer:
    performance_model:
      model: "pem_electrolyzer_performance"
    cost_model:
      model: "pem_electrolyzer_cost"
    model_inputs:
      shared_parameters:
        cluster_size_mw: 100.0
      performance_parameters:
        plant_life: 30
        eol_eff_percent_loss: 10
        uptime_hours_until_eol: 77600
        include_degradation_penalty: True
        turndown_ratio: 0.1
      cost_parameters:
        electrolyzer_cost: 2.
      financial_parameters:
        replacement_cost_percent: 0.

  ammonia:
    performance_model:
      model: "ammonia_performance"
    cost_model:
      model: "ammonia_cost"
    model_inputs:
      shared_parameters:
        plant_capacity_factor: 0.9
        plant_capacity_kgpy: 362560000.
      cost_parameters:
        # hydrogen_amount_kgpy: 73300000.
        feedstocks:
          electricity_cost: 93.83010424374427
          hydrogen_cost: 4.023963541079105
          cooling_water_cost: 0.00478
          iron_based_catalyst_cost: 23.19977341
          oxygen_cost: 0
      # financial_parameters:
      #   plant_life: 30
      #   grid_prices:
      #     '2035': 93.83010424374427
      #     '2036': 94.56653899260273
      #     '2037': 95.30297374146119
      #     '2038': 96.03940849031963
      #     '2039': 96.77584323917809
      #     '2040': 97.51227798803654
      #     '2041': 95.30655709762559
      #     '2042': 93.10083620721463
      #     '2043': 90.89511531680367
      #     '2044': 88.68939442639271
      #     '2045': 86.48367353598175
      #     '2046': 87.5303266407854
      #     '2047': 88.57697974558906
      #     '2048': 89.6236328503927
      #     '2049': 90.67028595519635
      #     '2050': 91.71693906
      #     '2051': 91.71693906
      #     '2052': 91.71693906
      #     '2053': 91.71693906
      #     '2054': 91.71693906
      #     '2055': 91.71693906
      #     '2056': 91.71693906
      #     '2057': 91.71693906
      #     '2058': 91.71693906
      #     '2059': 91.71693906
      #     '2060': 91.71693906
      #     '2061': 91.71693906
      #     '2062': 91.71693906
      #     '2063': 91.71693906
      #     '2064': 91.71693906

      #   # Additional parameters passed to ProFAST
      #   financial_assumptions:
      #     "total income tax rate": 0.2574
      #     "capital gains tax rate": 0.15
      #     "leverage after tax nominal discount rate": 0.10893
      #     "debt equity ratio of initial financing": 0.624788
      #     "debt interest rate": 0.050049
