name: "technology_config"
description: "This plant has wind and solar"

technologies:
  # Gen brought up idea to support multiple tech
  # definitions for a specific tech, e.g. multiple
  # battery types.
  solar:
    performance_model:
      model: "pysam_solar_plant_performance"
    model_inputs:
      panel_size: 1.
  wind:
    performance_model:
      model: "pysam_wind_plant_performance"
    cost_model:
      model: "wind_plant_cost"
    model_inputs:
      performance_parameters:
        hub_height: 115.0
      cost_parameters:
        num_turbines: 20
        turbine_rating_kw: 3000.0
        cost_per_kw: 1500.0
  combiner:
    performance_model:
      model: "combiner_performance"
  electrolyzer:
    performance_model:
      model: "pem_electrolyzer_performance"
    cost_model:
      model: "pem_electrolyzer_cost"
    model_inputs:
      shared_parameters:
        cluster_size_mw: 100.0
      performance_parameters:
        plant_life: 30
        eol_eff_percent_loss: 10
        uptime_hours_until_eol: 77600
        include_degradation_penalty: True
        turndown_ratio: 0.1
      cost_parameters:
        electrolyzer_cost: 2000.
