name: "technology_config"
description: "This plant has a wind turbine, just one"

technologies:
  # Gen brought up idea to support multiple tech
  # definitions for a specific tech, e.g. multiple
  # battery types.
  solar:
    performance_model:
      model: "pysam_solar_plant"
    cost_model:
      model: "wind_plant"
    details:
      panel_size: 1.
  electrolyzer:
    performance_model:
      model: "pem_electrolyzer"
    cost_model:
      model: "pem_electrolyzer"
    details:
      cluster_size_mw: 100.0
      electrolyzer_cost: 2000.
      plant_life: 30
      model_parameters:
        eol_eff_percent_loss: 10
        uptime_hours_until_eol: 77600
        include_degradation_penalty: True
        turndown_ratio: 0.1