name: "technology_config"
description: "This plant has a wind turbine, just one"

technologies:
  # Gen brought up idea to support multiple tech
  # definitions for a specific tech, e.g. multiple
  # battery types.
  wind:
    wind_location: "onshore"
    performance_model:
      model: "wind_plant"
    cost_model:
      model: "wind_plant"
  electrolyzer:
    performance_model:
      model: "dummy_electrolyzer"
    cost_model:
      model: "dummy_electrolyzer"