name: "plant_config"
description: "This plant is located in MN, USA..."

site:
  latitude: 47.5233
  longitude: -92.5366
  elevation_m: 439.0
  time_zone: -5

  # array of polygons defining boundaries with x/y coords
  boundaries: [
    {
      x: [0.0, 1000.0, 1000.0, 0.0],
      y: [0.0, 0.0, 100.0, 1000.0],
    },
    {
      x: [2000.0, 2500.0, 2000.0],
      y: [2000.0, 2000.0, 2500.0],
    }
  ]

# dictionary of energy resources; you only need to include
# resource files for technologies that are being used
energy_resources:
  wind: 
    type: "pysam_wind"
    wind_speed: 9.