name: "technology_config"
description: "This plant has a wind turbine, just one"

technologies:
  # Gen brought up idea to support multiple tech
  # definitions for a specific tech, e.g. multiple
  # battery types.
  wind:
    resource: 
      wind_speed: 9.
    performance_model:
      model: "dummy_wind_turbine_performance"
    cost_model:
      model: "dummy_wind_turbine_cost"