name: "plant_config"
description: "This plant is located in MN, USA..."

site:
  latitude: 47.5233
  longitude: -92.5366
  elevation_m: 439.0
  time_zone: -5

  # array of polygons defining boundaries with x/y coords
  boundaries: [
    {
      x: [0.0, 1000.0, 1000.0, 0.0],
      y: [0.0, 0.0, 100.0, 1000.0],
    },
    {
      x: [2000.0, 2500.0, 2000.0],
      y: [2000.0, 2000.0, 2500.0],
    }
  ]

plant:
  plant_life: 30.

# array of arrays containing left-to-right technology
# interconnections; can support bidirectional connections
# with the reverse definition.
# this will naturally grow as we mature the interconnected tech
technology_interconnections: [
  ["feedstocks", "electrolyzer", "electricity", "cable"],
  ["electrolyzer", "tank", "hydrogen", "pipe"]
  # etc
]

